version: '3.1'

services:
  redmine:
    container_name: redmine
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
      REDMINE_DB_ENCODING: utf8mb4
    volumes:
      - ./redmine/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./redmine/files:/usr/src/redmine/files
      - ./redmine/plugins:/usr/src/redmine/plugins

  redmine-db:
    container_name: redmine-db
    image: mysql:5.7
    restart: always
    command: --character-set-server=utf8mb4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    volumes:
      - ./redmine-db/data:/var/lib/mysql

  redmine-mail:
    container_name: redmine-mail
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
